#!/usr/bin/env php
<?php

/**
 * This file is used to manage the application on the command line. It won't execute in a browser environment.
 *
 * - Windows: `php ace --help`
 * - Linux: `ace --help`
 */
require_once __DIR__ . '/horizon/bootstrap/console.php';
