site_name: Horizon
site_url: https://docs.bailey.sh/horizon/
site_author: Bailey Herbert
site_description: Documentation for Horizon, a PHP web application framework based on Laravel that works on any server.

repo_name: baileyherbert/horizon
repo_url: https://github.com/baileyherbert/horizon
edit_uri: ""

theme:
  name: material
  custom_dir: docs/assets/overrides
  features:
    - navigation.tabs
    - navigation.top
    - navigation.tracking
    - navigation.sections
    - navigation.footer
  logo: assets/logo.png
  favicon: assets/logo.png
  palette:
    - scheme: default
      media: "(prefers-color-scheme: light)"
      primary: light blue
      accent: light blue
      toggle:
        icon: material/weather-night
        name: Switch to dark mode
    - scheme: slate
      media: "(prefers-color-scheme: dark)"
      primary: light blue
      accent: light blue
      toggle:
        icon: material/weather-sunny
        name: Switch to light mode
  icon:
    repo: fontawesome/brands/github

extra_css:
  - assets/styles.css

markdown_extensions:
  - attr_list
  - toc:
      permalink: True
      separator: "_"
  - admonition
  - footnotes
  - pymdownx.superfences:
  - pymdownx.highlight:
      extend_pygments_lang:
        - name: php
          lang: php
          options:
            startinline: true
  - pymdownx.saneheaders
  - pymdownx.tabbed
  - pymdownx.inlinehilite
  - pymdownx.emoji:
      emoji_index: !!python/name:material.extensions.emoji.twemoji
      emoji_generator: !!python/name:material.extensions.emoji.to_svg

nav:
  - Home: index.md

  - Getting started:
    - Requirements: getting-started/requirements.md
    - Installation: getting-started/installation.md
    - Configuration: getting-started/configuration.md

  - Reference:
    - Architecture:
      - File structure: reference/architecture/file-structure.md
      - Autoloader: reference/architecture/autoloader.md
      - Service container: reference/architecture/service-container.md
      - Service providers: reference/architecture/service-providers.md
      - Facades: reference/architecture/facades.md
      - Helpers: reference/architecture/helpers.md
    - Essentials:
      - Routing: reference/essentials/routing.md
      - Middleware: reference/essentials/middleware.md
      - Controllers: reference/essentials/controllers.md
      - Requests: reference/essentials/requests.md
      - Responses: reference/essentials/responses.md
      - Views: reference/essentials/views.md
      - Sessions: reference/essentials/sessions.md
      - Errors: reference/essentials/errors.md
      - Extensions: reference/essentials/extensions.md
    - Frontend:
      - Templates: reference/frontend/templates.md
      - Components: reference/frontend/components.md
      - Localization: reference/frontend/localization.md
    - Database:
      - Query builder: reference/database/query-builder.md
      - Migrations: reference/database/migrations.md
    - ORM:
      - Models: reference/orm/models.md
      - Relationships: reference/orm/relationships.md
      - Serialization: reference/orm/serialization.md

plugins:
  - search
  - minify:
      minify_html: true

extra:
  version:
    provider: mike
    default: latest
  social:
    - icon: fontawesome/brands/github
      link: https://github.com/baileyherbert
    - icon: fontawesome/brands/docker
      link: https://hub.docker.com/u/baileyherbert
